config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('login/', include('core.login.urls')),
    path("erp/", include("core.erp.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.replacement.views import *
from core.erp.views.client.views import *
from core.erp.views.dashboard.views import DashboardView
from core.erp.views.sale.views import *
from core.erp.views.pay_methods.views import *
from core.erp.views.cotizacion.views import *
from core.erp.views.money.views import *


app_name = 'erp'

urlpatterns = [
    #Category
    path('category/list/', CategoryListView.as_view(), name="category_list"),
    path('category/add/', CategoryCreateView.as_view(), name="category_create"),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name="category_update"),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name="category_delete"),
        
    #Replacement
    path('replacement/list/', ReplacementListView.as_view(), name="replacement_list"),
    path('replacement/add/', ReplacementCreateView.as_view(), name="replacement_create"),
    path('replacement/update/<int:pk>/', ReplacementUpdateView.as_view(), name="replacement_update"),
    path('replacement/delete/<int:pk>/', ReplacementDeleteView.as_view(), name="replacement_delete"),
    
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    
    #Customer
    path('client/list/', ClientListView.as_view(), name="client_list"),
    path('client/add/', ClientCreateView.as_view(), name="client_create"),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name="client_update"),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name="client_delete"),
    
    #Sale
    #path('sale/list/', SaleListView.as_view(), name="sale_list"),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    #path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    
    #Pay Methods
    path('pay_methods/list/', PayMethodListView.as_view(), name="pay_methods_list"),
    path('pay_methods/add/', PayMethodsCreateView.as_view(), name="pay_methods_create"),
    path('pay_methods/update/<int:pk>/', PayMethodsUpdateView.as_view(), name="pay_methods_update"),
    path('pay_methods/delete/<int:pk>/', PayMethodsDeleteView.as_view(), name="pay_methods_delete"),
    
    #Cotizaciones
    #path('cotizacion/list', CotizacionListView.as_view(), name="cotizacion_list"),
    #path('cotizacion/add/', CotizacionCreateView.as_view(), name='cotizacion_create'),
    #path('cotizacion/update/<int:pk>/', CotizacionUpdateView.as_view(), name='cotizacion_update'),
    #path('cotizacion/delete/<int:pk>/', CotizacionDeleteView.as_view(), name="cotizacion_delete"),
    #path('cotizacion/invoice/pdf/<int:pk>/', CotizacionInvoiceView.as_view(), name="cotizacion_invoice"),
    
    #Money
    path('money/list', MoneyListView.as_view(), name="money_list"),
    path('money/add/', MoneyCreateView.as_view(), name="money_create"),

]

templates/partials/delete.html
{% extends 'form.html' %}

{% load widget_tweaks %}

{% block content %}
  <form method="post" action=".">
    <div class="card card-primary">
      <div class="card-header" style="background-color: #FFFFFF">
        <h3 class="card-title" style="color: black;"><i class="fas fa-trash"></i> {{ title }}</h3>
      </div>
      <div class="card-body">
        {% csrf_token %}
        <input type="hidden" name="action" value="{{ action }}" /> {% if form.errors %}
          <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
            <ul>
              {% for field in form %}
                {% for error in field.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              {% endfor %}
            </ul>
          </div>
        {% endif %}
        <div class="alert alert-danger alert-dismissible">
          <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
          <!-- ¿Estas seguro de eliminar el registro N°{{ object.name }}? -->
          ¿Está seguro de eliminar este Item?
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-success btn-flat"><i class="fas fa-save"></i> Si, aceptar</button>
        <a href="{{ list_url }}" class="btn btn-danger btn-flat"><i class="fas fa-times"></i> Cancelar</a>
      </div>
    </div>
  </form>

  <script>
    $('form').on('submit', function (e) {
      e.preventDefault()
      var parameters = new FormData(this)
      submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
        Swal.fire({
          title: 'Alerta',
          text: 'Registro Eliminado Correctamente',
          icon: 'success',
          timer: 2000
        }).then((result) => {
          location.href = '{{ list_url }}'
        })
      })
    })
  </script>
{% endblock %}

templates/partials/footer.html
<!-- Main Footer -->
<!--

    <footer class="main-footer">
    To the right 
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    Default to the left 
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

-->

templates/partials/header.html
{% load static %}

<nav class="main-header navbar navbar-expand navbar-light" style="background-color: #FFFDF9;">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars" style="color: black;"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'erp:dashboard' %}" class="nav-link" style="color: black;">Inicio</a>
    </li>
  </ul>
  <ul class="order-1 order-md-3 navbar-no-expand navbar-nav ml-auto">
    <li class="nav-item dropdown" style="color: black;">
      <a class="nav-link" data-toggle="dropdown" href="#" style="color: black;">
        <i class="fas fa-users-cog" style="color: black;"></i>
        {{ request.user.username }}
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header" style="font-size: 12px; color: black">Último acceso: {{ request.user.last_login }}</span>
        <div class="dropdown-divider"></div>
        <a href="" class="dropdown-item"><i class="fas fa-edit mr-2" style="color: black;"></i> Editar perfil</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item dropdown-footer"></a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-power-off" aria-hidden="true" style="color: black;"></i></a>
    </li>
  </ul>
</nav>

templates/partials/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-primary elevation-4" style="background-color: #FFFDFF;">
  <a href="{% url 'erp:dashboard' %}" class="brand-link">
    <img src="{% static 'img/LogoMAQTEC.png' %}" alt="MACTECH Logo" class="brand-image elevation-3"/>
    <span class="brand-text font-weight-light" style="color: black;">ERP Management</span>
  </a>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <!-- <img src="{% static 'img/empty.png' %}" class="img-circle" alt="User Image" /> -->
      </div>
      <div class="info">
        <p>
          <a href="" class="d-block" style="color: black;">User:{{ request.user.username }}</a>
        </p>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-header" style="color:black">Módulos</li>

        <li class="nav-item menu-is-opening menu-open" style="color: black;">
          <a href="#" class="nav-link" style="color: black;">
            <i class="fas fa-pallet"></i>
            <p>
              Inventario
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: block;">
            <li class="nav-item">
              <a href="{% url 'erp:category_list' %}" class="nav-link" style="color:black">
                <i class="nav-icon fas fa-truck-loading"></i>
                <p>Categorías</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'erp:replacement_list' %}" class="nav-link" style="color:black">
                <i class="nav-icon fas fa-boxes"></i>
                <p>Repuestos</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'erp:pay_methods_list' %}" class="nav-link" style="color:black">
                <i class="fas fa-money-check"></i>
                <p>Medios de Pago</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'erp:money_list' %}" class="nav-link" style="color:black">
                <i class="fas fa-dollar-sign"></i>
                <p>Moneda</p>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item menu-is-opening menu-open" style="color: black;">
          <a href="#" class="nav-link" style="color: black;">
            <i class="fas fa-wrench"></i>
            <p>
              CRM
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview" style="display: block;">
            <li class="nav-item">
              <a href="{% url 'erp:client_list' %}" class="nav-link" style="color:black">
                <i class="nav-icon fas fa-users"></i>
                <p>Clientes</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'erp:cotizacion_list' %}" class="nav-link" style="color:black">
                <i class="fas fa-file-invoice"></i>
                <p>Generar Cotización</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="" class="nav-link" style="color:black">
                <i class="nav-icon fas fa-shopping-cart"></i>
                <p>Ventas</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>